name: Build TWRP Recovery

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Initialize Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev libc6-dev-i386 x11proto-core-dev libx11-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

      - name: Install Repo Tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+rx ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Initialize TWRP Repo
        run: |
          mkdir ~/twrp
          cd ~/twrp
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1

      - name: Clone Device Tree
        run: |
          cd ~/twrp
          git clone ${{ github.server_url }}/${{ github.repository }} -b ${{ github.ref_name }} device/ant/B2_Ultra

      - name: Repo Sync
        run: |
          cd ~/twrp
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Build Recovery Image
        run: |
          cd ~/twrp
          source build/envsetup.sh
          lunch twrp_B2_Ultra-eng
          mka recoveryimage -j$(nproc --all)

      - name: Upload Recovery Image
        uses: actions/upload-artifact@v4
        with:
          name: twrp-B2_Ultra
          path: |
            ~/twrp/out/target/product/B2_Ultra/recovery.img
            ~/twrp/out/target/product/B2_Ultra/boot.img
